# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_contact_number',
            field=models.CharField(default=9175958762, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_contact_number',
            field=models.CharField(default=8830310738, max_length=10),
            preserve_default=False,
        ),
    ]
