# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 08:55
from __future__ import unicode_literals

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20171228_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.get_image_path),
        ),
    ]
